<a href="https://colab.research.google.com/github/mustaf2007/QFI-Market-Risk-Modelling/blob/main/Mustaf_Task_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#installing Yahoo Finance

In [ ]:
!pip install yfinance -q

#Importing the libraries

In [ ]:
import yfinance as yf
import pandas as pd
import numpy as np

#Defining the 10 stocks

In [ ]:
tickers = [
    "AAPL",   # Apple
    "MSFT",   # Microsoft
    "NVDA",   # NVIDIA
    "JPM",    # JPMorgan Chase
    "XOM",    # Exxon Mobil
    "AMZN",   # Amazon
    "META",   # Meta Platforms
    "GOOGL",  # Alphabet
    "TSLA",   # Tesla
    "UNH"     # UnitedHealth
]

print("Number of stocks:", len(tickers))
print(tickers)

Number of stocks: 10
['AAPL', 'MSFT', 'NVDA', 'JPM', 'XOM', 'AMZN', 'META', 'GOOGL', 'TSLA', 'UNH']

#Choosing the historical period

In [ ]:
start_date = "2020-01-01"
end_date = "2026-07-26"

#Downloading the data from Yahoo Finance

In [ ]:
data = yf.download(
    tickers,
    start=start_date,
    end=end_date,
    auto_adjust=False,
    progress=False
)

print(data.head())

Price       Adj Close                                                \
Ticker           AAPL       AMZN      GOOGL         JPM        META
Date
2020-01-02  72.333893  94.900497  67.832504  117.899216  207.953857
2020-01-03  71.630646  93.748497  67.477661  116.343353  206.853485
2020-01-06  72.201416  95.143997  69.276230  116.250847  210.749283
2020-01-07  71.861847  95.343002  69.142403  114.274513  211.205307
2020-01-08  73.017830  94.598503  69.634537  115.165947  213.346466

Price                                                               ...  \
Ticker            MSFT      NVDA       TSLA         UNH        XOM  ...
Date                                                                ...
2020-01-02  151.829559  5.963803  28.684000  261.702240  52.947033  ...
2020-01-03  149.939011  5.868347  29.534000  259.053772  52.521362  ...
2020-01-06  150.326569  5.892957  30.102667  260.852173  52.924625  ...
2020-01-07  148.955902  5.964300  31.270666  259.277527  52.491493  ...
2020-01-08  151.328598  5.975487  32.809334  264.744171  51.699909  ...

Price          Volume                                                    \
Ticker           AAPL      AMZN     GOOGL       JPM      META      MSFT
Date
2020-01-02  135480400  80580000  27278000  10803700  12077100  22622100
2020-01-03  146322800  75288000  23408000  10386800  11188400  21116200
2020-01-06  118387200  81236000  46768000  10259000  17058900  20813700
2020-01-07  108872000  80898000  34330000  10531300  14912400  21634100
2020-01-08  132079200  70160000  35314000   9695300  13475000  27746500

Price
Ticker           NVDA       TSLA      UNH       XOM
Date
2020-01-02  237536000  142981500  2543400  12456400
2020-01-03  205384000  266677500  2711400  17386900
2020-01-06  262636000  151995000  3079100  20081900
2020-01-07  314856000  268231500  2492900  17387700
2020-01-08  277108000  467164500  3379200  15137700

[5 rows x 60 columns]

#Extracting adjusted closing prices

In [ ]:
prices = data["Adj Close"].copy()

print(prices.head())

Ticker           AAPL       AMZN      GOOGL         JPM        META  \
Date
2020-01-02  72.333893  94.900497  67.832504  117.899216  207.953857
2020-01-03  71.630646  93.748497  67.477661  116.343353  206.853485
2020-01-06  72.201416  95.143997  69.276230  116.250847  210.749283
2020-01-07  71.861847  95.343002  69.142403  114.274513  211.205307
2020-01-08  73.017830  94.598503  69.634537  115.165947  213.346466

Ticker            MSFT      NVDA       TSLA         UNH        XOM
Date
2020-01-02  151.829559  5.963803  28.684000  261.702240  52.947033
2020-01-03  149.939011  5.868347  29.534000  259.053772  52.521362
2020-01-06  150.326569  5.892957  30.102667  260.852173  52.924625
2020-01-07  148.955902  5.964300  31.270666  259.277527  52.491493
2020-01-08  151.328598  5.975487  32.809334  264.744171  51.699909

#Inspecting the data

In [ ]:
print("Dataset shape:", prices.shape)

print("\nDate range:")
print("Start:", prices.index.min())
print("End:", prices.index.max())

print("\nMissing values:")
print(prices.isna().sum())

print("\nFirst 5 rows:")
print(prices.head())

print("\nLast 5 rows:")
print(prices.tail())

Dataset shape: (1648, 10)

Date range:
Start: 2020-01-02 00:00:00
End: 2026-07-24 00:00:00

Missing values:
Ticker
AAPL     0
AMZN     0
GOOGL    0
JPM      0
META     0
MSFT     0
NVDA     0
TSLA     0
UNH      0
XOM      0
dtype: int64

First 5 rows:
Ticker           AAPL       AMZN      GOOGL         JPM        META  \
Date
2020-01-02  72.333893  94.900497  67.832504  117.899216  207.953857
2020-01-03  71.630646  93.748497  67.477661  116.343353  206.853485
2020-01-06  72.201416  95.143997  69.276230  116.250847  210.749283
2020-01-07  71.861847  95.343002  69.142403  114.274513  211.205307
2020-01-08  73.017830  94.598503  69.634537  115.165947  213.346466

Ticker            MSFT      NVDA       TSLA         UNH        XOM
Date
2020-01-02  151.829559  5.963803  28.684000  261.702240  52.947033
2020-01-03  149.939011  5.868347  29.534000  259.053772  52.521362
2020-01-06  150.326569  5.892957  30.102667  260.852173  52.924625
2020-01-07  148.955902  5.964300  31.270666  259.277527  52.491493
2020-01-08  151.328598  5.975487  32.809334  264.744171  51.699909

Last 5 rows:
Ticker            AAPL        AMZN       GOOGL         JPM        META  \
Date
2026-07-20  326.589996  249.990005  351.989990  338.869995  645.849976
2026-07-21  327.739990  247.550003  347.149994  345.230011  643.809998
2026-07-22  325.890015  244.850006  342.089996  348.209991  627.169983
2026-07-23  321.660004  233.660004  317.690002  349.899994  606.099976
2026-07-24  333.019989  232.110001  319.739990  353.209991  595.190002

Ticker            MSFT        NVDA        TSLA         UNH         XOM
Date
2026-07-20  402.290009  203.279999  369.570007  421.549988  148.360001
2026-07-21  397.750000  207.289993  378.929993  436.350006  151.710007
2026-07-22  390.339996  212.059998  374.010010  431.309998  154.449997
2026-07-23  381.579987  208.759995  319.690002  423.559998  156.889999
2026-07-24  381.700012  206.839996  313.029999  420.739990  156.940002

In [ ]:
prices.describe()

Ticker,AAPL,AMZN,GOOGL,JPM,META,MSFT,NVDA,TSLA,UNH,XOM
count,1648.000000,1648.000000,1648.000000,1648.000000,1648.000000,1648.000000,1648.000000,1648.000000,1648.000000,1648.000000
mean,174.323855,165.135221,150.814975,170.793130,382.638746,322.664230,69.241833,251.267402,404.832505,84.871630
std,57.558765,44.496636,75.090708,73.897559,187.905629,100.179000,66.579356,104.175002,93.677926,33.959161
min,54.163704,81.820000,52.243248,66.463898,88.136040,128.358337,4.885130,24.081333,175.098022,23.823561
25%,135.564079,129.812504,101.525623,117.892139,228.746258,239.272259,15.305217,188.237503,315.834702,51.199953
50%,168.531166,163.767502,134.061241,139.424332,322.349243,313.104858,29.934595,242.294998,429.285751,95.354027
75%,216.529335,193.882504,169.908398,227.194073,567.660919,408.362137,125.949911,325.309998,479.841377,107.248604
max,333.739990,274.989990,402.379669,353.209991,787.419189,538.658508,235.465576,489.880005,599.775635,170.313995

#Calculating daily log returns

In [ ]:
returns = np.log(prices / prices.shift(1))

returns = returns.dropna(how="all")

print(returns.head())

Ticker          AAPL      AMZN     GOOGL       JPM      META      MSFT  \
Date
2020-01-03 -0.009770 -0.012213 -0.005245 -0.013284 -0.005305 -0.012530
2020-01-06  0.007937  0.014776  0.026305 -0.000795  0.018658  0.002581
2020-01-07 -0.004714  0.002089 -0.001934 -0.017147  0.002161 -0.009160
2020-01-08  0.015958 -0.007839  0.007092  0.007771  0.010087  0.015803
2020-01-09  0.021019  0.004788  0.010443  0.003645  0.014210  0.012415

Ticker          NVDA      TSLA       UNH       XOM
Date
2020-01-03 -0.016135  0.029203 -0.010172 -0.008072
2020-01-06  0.004185  0.019072  0.006918  0.007649
2020-01-07  0.012034  0.038067 -0.006055 -0.008218
2020-01-08  0.001874  0.048033  0.020865 -0.015195
2020-01-09  0.010923 -0.022189 -0.005694  0.007626

#Checking the returns

In [ ]:
print("Returns shape:", returns.shape)

print("\nMissing values:")
print(returns.isna().sum())

print("\nSummary statistics:")
print(returns.describe())

Returns shape: (1647, 10)

Missing values:
Ticker
AAPL     0
AMZN     0
GOOGL    0
JPM      0
META     0
MSFT     0
NVDA     0
TSLA     0
UNH      0
XOM      0
dtype: int64

Summary statistics:
Ticker         AAPL         AMZN        GOOGL          JPM         META  \
count   1647.000000  1647.000000  1647.000000  1647.000000  1647.000000
mean       0.000927     0.000543     0.000941     0.000666     0.000638
std        0.019741     0.022242     0.020453     0.019379     0.027767
min       -0.137708    -0.151398    -0.123684    -0.162106    -0.306391
25%       -0.008191    -0.011209    -0.009592    -0.008003    -0.011960
50%        0.001139     0.000768     0.001536     0.001033     0.000912
75%        0.011155     0.012884     0.011559     0.009928     0.013895
max        0.142618     0.126949     0.097348     0.165621     0.209307

Ticker         MSFT         NVDA         TSLA          UNH          XOM
count   1647.000000  1647.000000  1647.000000  1647.000000  1647.000000
mean       0.000560     0.002153     0.001451     0.000288     0.000660
std        0.018840     0.032628     0.040964     0.021943     0.020509
min       -0.159453    -0.203979    -0.236518    -0.253341    -0.130391
25%       -0.008528    -0.015574    -0.020404    -0.008290    -0.010203
50%        0.000785     0.002965     0.001534     0.000734     0.000771
75%        0.010426     0.020884     0.022528     0.009585     0.011707
max        0.132929     0.218088     0.204491     0.120437     0.119442

In [ ]:
# Save adjusted closing prices
prices.to_csv("Raw_Portfolio_Prices.csv")

# Save daily log returns
returns.to_csv("Portfolio_Returns.csv")

print("Files saved successfully!")
print("Raw_Portfolio_Prices.csv:", prices.shape)
print("Portfolio_Returns.csv:", returns.shape)

Files saved successfully!
Raw_Portfolio_Prices.csv: (1648, 10)
Portfolio_Returns.csv: (1647, 10)

In [ ]:
# Create equal portfolio weights
weights = pd.Series(
    1 / len(tickers),
    index=tickers,
    name="Weight"
)

print(weights)
print("\nNumber of stocks:", len(weights))
print("Total weight:", weights.sum())

AAPL     0.1
MSFT     0.1
NVDA     0.1
JPM      0.1
XOM      0.1
AMZN     0.1
META     0.1
GOOGL    0.1
TSLA     0.1
UNH      0.1
Name: Weight, dtype: float64

Number of stocks: 10
Total weight: 1.0

In [ ]:
weights.to_csv("Portfolio_Weights.csv", header=True)

print("Portfolio weights saved.")

Portfolio weights saved.

In [ ]:
# Download S&P 500 market index data
market_data = yf.download(
    "^GSPC",
    start="2020-01-01",
    end="2026-07-26",
    auto_adjust=False,
    progress=False
)

print(market_data.head())
print("\nShape:", market_data.shape)

Price         Adj Close        Close         High          Low         Open  \
Ticker            ^GSPC        ^GSPC        ^GSPC        ^GSPC        ^GSPC
Date
2020-01-02  3257.850098  3257.850098  3258.139893  3235.530029  3244.669922
2020-01-03  3234.850098  3234.850098  3246.149902  3222.340088  3226.360107
2020-01-06  3246.280029  3246.280029  3246.840088  3214.639893  3217.550049
2020-01-07  3237.179932  3237.179932  3244.909912  3232.429932  3241.860107
2020-01-08  3253.050049  3253.050049  3267.070068  3236.669922  3238.590088

Price           Volume
Ticker           ^GSPC
Date
2020-01-02  3459930000
2020-01-03  3484700000
2020-01-06  3702460000
2020-01-07  3435910000
2020-01-08  3726840000

Shape: (1648, 6)

In [ ]:
# Extract S&P 500 adjusted closing prices
market_prices = market_data["Adj Close"].copy()

market_prices.columns = ["SP500"]

print(market_prices.head())
print("\nShape:", market_prices.shape)
print("\nMissing values:")
print(market_prices.isna().sum())

                  SP500
Date
2020-01-02  3257.850098
2020-01-03  3234.850098
2020-01-06  3246.280029
2020-01-07  3237.179932
2020-01-08  3253.050049

Shape: (1648, 1)

Missing values:
SP500    0
dtype: int64

In [ ]:
market_prices.to_csv("Market_Index_Prices.csv")

print("Market index prices saved.")

Market index prices saved.

In [ ]:
print("PHASE 1 SUMMARY")
print("-" * 40)

print("Stock price matrix:", prices.shape)
print("Stock return matrix:", returns.shape)
print("Number of portfolio weights:", len(weights))
print("Weights total:", weights.sum())
print("Market index matrix:", market_prices.shape)

print("\nStock price missing values:")
print(prices.isna().sum())

print("\nStock return missing values:")
print(returns.isna().sum())

print("\nMarket index missing values:")
print(market_prices.isna().sum())

PHASE 1 SUMMARY
----------------------------------------
Stock price matrix: (1648, 10)
Stock return matrix: (1647, 10)
Number of portfolio weights: 10
Weights total: 1.0
Market index matrix: (1648, 1)

Stock price missing values:
Ticker
AAPL     0
AMZN     0
GOOGL    0
JPM      0
META     0
MSFT     0
NVDA     0
TSLA     0
UNH      0
XOM      0
dtype: int64

Stock return missing values:
Ticker
AAPL     0
AMZN     0
GOOGL    0
JPM      0
META     0
MSFT     0
NVDA     0
TSLA     0
UNH      0
XOM      0
dtype: int64

Market index missing values:
SP500    0
dtype: int64

In [ ]:
# Preserve Phase 1 data
clean_prices = prices.copy()
clean_market = market_prices.copy()

print("Stock prices:", clean_prices.shape)
print("Market index:", clean_market.shape)

Stock prices: (1648, 10)
Market index: (1648, 1)

In [ ]:
auto_adjust=False

Daily adjusted close prices obtained from Yahoo Finance are used. These prices account for corporate actions such as stock splits and dividends, avoiding the need for manual price adjustment.

In [ ]:
print("Stock dates:", len(clean_prices.index))
print("Market dates:", len(clean_market.index))

print("\nSame dates:",
      clean_prices.index.equals(clean_market.index))

print("\nStock start:", clean_prices.index.min())
print("Stock end:", clean_prices.index.max())

print("\nMarket start:", clean_market.index.min())
print("Market end:", clean_market.index.max())

Stock dates: 1648
Market dates: 1648

Same dates: True

Stock start: 2020-01-02 00:00:00
Stock end: 2026-07-24 00:00:00

Market start: 2020-01-02 00:00:00
Market end: 2026-07-24 00:00:00

In [ ]:
common_dates = clean_prices.index.intersection(clean_market.index)

clean_prices = clean_prices.loc[common_dates]
clean_market = clean_market.loc[common_dates]

print("Common trading dates:", len(common_dates))
print("Clean stock prices:", clean_prices.shape)
print("Clean market index:", clean_market.shape)

print("\nDates aligned:",
      clean_prices.index.equals(clean_market.index))

Common trading dates: 1648
Clean stock prices: (1648, 10)
Clean market index: (1648, 1)

Dates aligned: True

In [ ]:
# Phase 2: Data integrity checks

print("=== MISSING VALUES ===")
print("\nStock prices:")
print(clean_prices.isna().sum())

print("\nMarket index:")
print(clean_market.isna().sum())

print("\n=== DUPLICATE DATES ===")
print("Stock duplicate dates:", clean_prices.index.duplicated().sum())
print("Market duplicate dates:", clean_market.index.duplicated().sum())

print("\n=== INVALID PRICES ===")
print("Stock prices <= 0:", (clean_prices <= 0).sum().sum())
print("Market prices <= 0:", (clean_market <= 0).sum().sum())

=== MISSING VALUES ===

Stock prices:
Ticker
AAPL     0
AMZN     0
GOOGL    0
JPM      0
META     0
MSFT     0
NVDA     0
TSLA     0
UNH      0
XOM      0
dtype: int64

Market index:
SP500    0
dtype: int64

=== DUPLICATE DATES ===
Stock duplicate dates: 0
Market duplicate dates: 0

=== INVALID PRICES ===
Stock prices <= 0: 0
Market prices <= 0: 0

In [ ]:
# Check consecutive unchanged prices
price_changes = clean_prices.diff()

stale_counts = (price_changes == 0).sum()

print("=== UNCHANGED PRICE OBSERVATIONS ===")
print(stale_counts.sort_values(ascending=False))

=== UNCHANGED PRICE OBSERVATIONS ===
Ticker
AAPL     4
AMZN     3
JPM      3
XOM      3
META     2
GOOGL    2
MSFT     2
NVDA     2
TSLA     1
UNH      1
dtype: int64

In [ ]:
# Display dates where a stock price was unchanged
for ticker in clean_prices.columns:
    stale_dates = clean_prices.index[clean_prices[ticker].diff() == 0]

    if len(stale_dates) > 0:
        print(f"\n{ticker}: {len(stale_dates)} unchanged observations")
        print(stale_dates.tolist())

AAPL: 4 unchanged observations
[Timestamp('2020-07-02 00:00:00'), Timestamp('2022-06-27 00:00:00'), Timestamp('2023-05-16 00:00:00'), Timestamp('2024-11-12 00:00:00')]

AMZN: 3 unchanged observations
[Timestamp('2023-09-27 00:00:00'), Timestamp('2023-09-28 00:00:00'), Timestamp('2024-03-21 00:00:00')]

GOOGL: 2 unchanged observations
[Timestamp('2022-12-01 00:00:00'), Timestamp('2024-10-03 00:00:00')]

JPM: 3 unchanged observations
[Timestamp('2020-02-12 00:00:00'), Timestamp('2020-02-20 00:00:00'), Timestamp('2025-04-30 00:00:00')]

META: 2 unchanged observations
[Timestamp('2023-06-02 00:00:00'), Timestamp('2024-09-10 00:00:00')]

MSFT: 2 unchanged observations
[Timestamp('2020-10-16 00:00:00'), Timestamp('2021-10-08 00:00:00')]

NVDA: 2 unchanged observations
[Timestamp('2021-11-12 00:00:00'), Timestamp('2023-12-29 00:00:00')]

TSLA: 1 unchanged observations
[Timestamp('2022-12-01 00:00:00')]

UNH: 1 unchanged observations
[Timestamp('2020-12-08 00:00:00')]

XOM: 3 unchanged observations
[Timestamp('2024-02-16 00:00:00'), Timestamp('2024-03-22 00:00:00'), Timestamp('2025-12-11 00:00:00')]

In [ ]:
# Inspect unchanged-price observations with surrounding dates

for ticker in clean_prices.columns:
    stale_positions = np.where(clean_prices[ticker].diff().eq(0))[0]

    if len(stale_positions) > 0:
        print(f"\n{'='*50}")
        print(f"{ticker}")
        print(f"{'='*50}")

        for pos in stale_positions:
            start = max(0, pos - 1)
            end = min(len(clean_prices), pos + 2)

            print(clean_prices[ticker].iloc[start:end])
            print()

==================================================
AAPL
==================================================
Date
2020-07-01    88.135361
2020-07-02    88.135361
2020-07-06    90.492989
Name: AAPL, dtype: float64

Date
2022-06-24    138.872253
2022-06-27    138.872253
2022-06-28    134.735321
Name: AAPL, dtype: float64

Date
2023-05-15    169.691086
2023-05-16    169.691086
2023-05-17    170.302490
Name: AAPL, dtype: float64

Date
2024-11-11    222.806458
2024-11-12    222.806458
2024-11-13    223.690826
Name: AAPL, dtype: float64


==================================================
AMZN
==================================================
Date
2023-09-26    125.980003
2023-09-27    125.980003
2023-09-28    125.980003
Name: AMZN, dtype: float64

Date
2023-09-27    125.980003
2023-09-28    125.980003
2023-09-29    127.120003
Name: AMZN, dtype: float64

Date
2024-03-20    178.149994
2024-03-21    178.149994
2024-03-22    178.869995
Name: AMZN, dtype: float64


==================================================
GOOGL
==================================================
Date
2022-11-30    100.102379
2022-12-01    100.102379
2022-12-02     99.557190
Name: GOOGL, dtype: float64

Date
2024-10-02    164.809296
2024-10-03    164.809296
2024-10-04    166.001678
Name: GOOGL, dtype: float64


==================================================
JPM
==================================================
Date
2020-02-11    116.057434
2020-02-12    116.057434
2020-02-13    115.956512
Name: JPM, dtype: float64

Date
2020-02-19    115.628532
2020-02-20    115.628532
2020-02-21    114.215622
Name: JPM, dtype: float64

Date
2025-04-29    238.877274
2025-04-30    238.877274
2025-05-01    241.093979
Name: JPM, dtype: float64


==================================================
META
==================================================
Date
2023-06-01    270.236908
2023-06-02    270.236908
2023-06-05    269.027496
Name: META, dtype: float64

Date
2024-09-09    501.423981
2024-09-10    501.423981
2024-09-11    508.417084
Name: META, dtype: float64


==================================================
MSFT
==================================================
Date
2020-10-15    209.290100
2020-10-16    209.290100
2020-10-19    204.106918
Name: MSFT, dtype: float64

Date
2021-10-07    283.508301
2021-10-08    283.508301
2021-10-11    282.912170
Name: MSFT, dtype: float64


==================================================
NVDA
==================================================
Date
2021-11-11    30.290588
2021-11-12    30.290588
2021-11-15    29.926781
Name: NVDA, dtype: float64

Date
2023-12-28    49.434135
2023-12-29    49.434135
2024-01-02    48.082527
Name: NVDA, dtype: float64


==================================================
TSLA
==================================================
Date
2022-11-30    194.699997
2022-12-01    194.699997
2022-12-02    194.860001
Name: TSLA, dtype: float64


==================================================
UNH
==================================================
Date
2020-12-07    316.355225
2020-12-08    316.355225
2020-12-09    313.217712
Name: UNH, dtype: float64


==================================================
XOM
==================================================
Date
2024-02-15    96.355820
2024-02-16    96.355820
2024-02-20    95.445503
Name: XOM, dtype: float64

Date
2024-03-21    105.421989
2024-03-22    105.421989
2024-03-25    106.499519
Name: XOM, dtype: float64

Date
2025-12-10    117.947929
2025-12-11    117.947929
2025-12-12    117.237518
Name: XOM, dtype: float64

In [ ]:
clean_prices.loc[
    "2023-09-25":"2023-10-02",
    "AMZN"
]

Date
2023-09-25    131.270004
2023-09-26    125.980003
2023-09-27    125.980003
2023-09-28    125.980003
2023-09-29    127.120003
2023-10-02    129.460007
Name: AMZN, dtype: float64

In [ ]:
# Maximum consecutive unchanged-price runs

for ticker in clean_prices.columns:
    unchanged = clean_prices[ticker].diff().eq(0)

    groups = (~unchanged).cumsum()
    runs = unchanged.groupby(groups).sum()

    max_run = int(runs.max())

    print(f"{ticker}: maximum unchanged run = {max_run} day(s)")

AAPL: maximum unchanged run = 1 day(s)
AMZN: maximum unchanged run = 2 day(s)
GOOGL: maximum unchanged run = 1 day(s)
JPM: maximum unchanged run = 1 day(s)
META: maximum unchanged run = 1 day(s)
MSFT: maximum unchanged run = 1 day(s)
NVDA: maximum unchanged run = 1 day(s)
TSLA: maximum unchanged run = 1 day(s)
UNH: maximum unchanged run = 1 day(s)
XOM: maximum unchanged run = 1 day(s)

Stale Price Check: Unchanged adjusted closing prices were identified and examined across all stocks. Most occurred for only one trading day, while AMZN had a maximum sequence of two consecutive unchanged observations. No prolonged stale-price patterns were identified; therefore, no observations were removed.

In [ ]:
# Calculate clean daily log returns
clean_returns = np.log(
    clean_prices / clean_prices.shift(1)
)

# Remove first row because no previous observation exists
clean_returns = clean_returns.dropna()

print("Clean returns shape:", clean_returns.shape)

print("\nMissing values:")
print(clean_returns.isna().sum())

print("\nInfinite values:")
print(np.isinf(clean_returns).sum())

print("\nFirst 5 observations:")
print(clean_returns.head())

Clean returns shape: (1647, 10)

Missing values:
Ticker
AAPL     0
AMZN     0
GOOGL    0
JPM      0
META     0
MSFT     0
NVDA     0
TSLA     0
UNH      0
XOM      0
dtype: int64

Infinite values:
Ticker
AAPL     0
AMZN     0
GOOGL    0
JPM      0
META     0
MSFT     0
NVDA     0
TSLA     0
UNH      0
XOM      0
dtype: int64

First 5 observations:
Ticker          AAPL      AMZN     GOOGL       JPM      META      MSFT  \
Date
2020-01-03 -0.009770 -0.012213 -0.005245 -0.013284 -0.005305 -0.012530
2020-01-06  0.007937  0.014776  0.026305 -0.000795  0.018658  0.002581
2020-01-07 -0.004714  0.002089 -0.001934 -0.017147  0.002161 -0.009160
2020-01-08  0.015958 -0.007839  0.007092  0.007771  0.010087  0.015803
2020-01-09  0.021019  0.004788  0.010443  0.003645  0.014210  0.012415

Ticker          NVDA      TSLA       UNH       XOM
Date
2020-01-03 -0.016135  0.029203 -0.010172 -0.008072
2020-01-06  0.004185  0.019072  0.006918  0.007649
2020-01-07  0.012034  0.038067 -0.006055 -0.008218
2020-01-08  0.001874  0.048033  0.020865 -0.015195
2020-01-09  0.010923 -0.022189 -0.005694  0.007626

In [ ]:
# Compare Phase 1 returns with Phase 2 clean returns

print("Same shape:",
      returns.shape == clean_returns.shape)

print("Same dates:",
      returns.index.equals(clean_returns.index))

print("Maximum difference:",
      (returns - clean_returns).abs().max().max())

Same shape: True
Same dates: True
Maximum difference: 0.0

In [ ]:
# Identify minimum and maximum daily log returns for each stock

extreme_summary = pd.DataFrame({
    "Min Return": clean_returns.min(),
    "Min Date": clean_returns.idxmin(),
    "Max Return": clean_returns.max(),
    "Max Date": clean_returns.idxmax()
})

print("=== EXTREME RETURN SUMMARY ===")
print(extreme_summary)

=== EXTREME RETURN SUMMARY ===
        Min Return   Min Date  Max Return   Max Date
Ticker
AAPL     -0.137708 2020-03-16    0.142618 2025-04-09
AMZN     -0.151398 2022-04-29    0.126949 2022-02-04
GOOGL    -0.123684 2020-03-16    0.097348 2024-04-26
JPM      -0.162106 2020-03-16    0.165621 2020-03-13
META     -0.306391 2022-02-03    0.209307 2023-02-02
MSFT     -0.159453 2020-03-16    0.132929 2020-03-13
NVDA     -0.203979 2020-03-16    0.218088 2023-05-25
TSLA     -0.236518 2020-09-08    0.204491 2025-04-09
UNH      -0.253341 2025-04-17    0.120437 2020-03-24
XOM      -0.130391 2020-03-09    0.119442 2020-03-24

In [ ]:
# Identify returns with absolute movement greater than 10%

threshold = 0.10

for ticker in clean_returns.columns:
    extreme = clean_returns.loc[
        clean_returns[ticker].abs() > threshold,
        ticker
    ]

    print(f"\n{ticker}: {len(extreme)} observations > 10%")

    if len(extreme) > 0:
        print(extreme)

AAPL: 4 observations > 10%
Date
2020-03-12   -0.103978
2020-03-13    0.113157
2020-03-16   -0.137708
2025-04-09    0.142618
Name: AAPL, dtype: float64

AMZN: 4 observations > 10%
Date
2022-02-04    0.126949
2022-04-29   -0.151398
2022-11-10    0.114915
2025-04-09    0.113124
Name: AMZN, dtype: float64

GOOGL: 1 observations > 10%
Date
2020-03-16   -0.123684
Name: GOOGL, dtype: float64

JPM: 7 observations > 10%
Date
2020-03-09   -0.145552
2020-03-13    0.165621
2020-03-16   -0.162106
2020-03-18   -0.111232
2020-03-24    0.112384
2020-11-09    0.126978
2024-11-06    0.109254
Name: JPM, dtype: float64

META: 11 observations > 10%
Date
2020-03-16   -0.153769
2022-02-03   -0.306391
2022-04-28    0.162064
2022-10-27   -0.281794
2023-02-02    0.209307
2023-04-27    0.130374
2024-02-02    0.184965
2024-04-25   -0.111617
2025-04-09    0.137634
2025-07-31    0.106634
2025-10-30   -0.120302
Name: META, dtype: float64

MSFT: 3 observations > 10%
Date
2020-03-13    0.132929
2020-03-16   -0.159453
2026-01-29   -0.105284
Name: MSFT, dtype: float64

NVDA: 15 observations > 10%
Date
2020-03-12   -0.130528
2020-03-13    0.107420
2020-03-16   -0.203979
2020-03-17    0.100988
2020-03-24    0.158340
2021-11-04    0.113706
2022-11-10    0.133912
2023-02-23    0.131216
2023-05-25    0.218088
2024-02-22    0.151870
2024-04-19   -0.105412
2024-07-31    0.120553
2024-09-03   -0.100097
2025-01-27   -0.185946
2025-04-09    0.171621
Name: NVDA, dtype: float64

TSLA: 47 observations > 10%
Date
2020-02-03    0.181445
2020-02-04    0.128619
2020-02-05   -0.188450
2020-02-27   -0.137133
2020-03-02    0.107257
2020-03-09   -0.145865
2020-03-12   -0.123493
2020-03-16   -0.205522
2020-03-18   -0.174763
2020-03-19    0.168795
2020-03-24    0.150846
2020-04-13    0.127547
2020-05-01   -0.108737
2020-07-06    0.126451
2020-07-10    0.102419
2020-08-12    0.123311
2020-08-17    0.106188
2020-08-31    0.118395
2020-09-08   -0.236518
2020-09-09    0.103669
2020-09-14    0.118522
2020-09-23   -0.109158
2021-03-09    0.179327
2021-10-25    0.119218
2021-11-09   -0.127723
2022-01-03    0.126912
2022-01-27   -0.122780
2022-01-31    0.101451
2022-04-26   -0.129928
2022-12-27   -0.121138
2023-01-03   -0.130590
2023-01-26    0.104065
2023-01-27    0.104362
2023-04-20   -0.102540
2023-07-20   -0.102443
2024-01-25   -0.129258
2024-04-24    0.113874
2024-04-29    0.142427
2024-07-24   -0.131643
2024-10-24    0.198187
2024-11-06    0.137595
2025-03-10   -0.167546
2025-03-24    0.112735
2025-04-04   -0.110036
2025-04-09    0.204491
2025-06-05   -0.153849
2026-07-23   -0.156931
Name: TSLA, dtype: float64

UNH: 10 observations > 10%
Date
2020-03-04    0.101827
2020-03-12   -0.103730
2020-03-16   -0.189671
2020-03-18   -0.117896
2020-03-24    0.120437
2025-04-17   -0.253341
2025-05-13   -0.195862
2025-05-15   -0.115728
2025-08-15    0.113135
2026-01-27   -0.218222
Name: UNH, dtype: float64

XOM: 6 observations > 10%
Date
2020-03-09   -0.130391
2020-03-12   -0.121422
2020-03-16   -0.100070
2020-03-18   -0.105632
2020-03-24    0.119442
2020-11-09    0.119206
Name: XOM, dtype: float64

In [ ]:
# Show prices surrounding each stock's minimum and maximum return

for ticker in clean_returns.columns:

    min_date = clean_returns[ticker].idxmin()
    max_date = clean_returns[ticker].idxmax()

    print("\n" + "=" * 60)
    print(ticker)
    print("=" * 60)

    print("\nLargest negative return:")
    print("Date:", min_date)
    print("Return:", clean_returns.loc[min_date, ticker])

    min_pos = clean_prices.index.get_loc(min_date)
    print(
        clean_prices[ticker].iloc[
            max(0, min_pos - 1): min(len(clean_prices), min_pos + 2)
        ]
    )

    print("\nLargest positive return:")
    print("Date:", max_date)
    print("Return:", clean_returns.loc[max_date, ticker])

    max_pos = clean_prices.index.get_loc(max_date)
    print(
        clean_prices[ticker].iloc[
            max(0, max_pos - 1): min(len(clean_prices), max_pos + 2)
        ]
    )

============================================================
AAPL
============================================================

Largest negative return:
Date: 2020-03-16 00:00:00
Return: -0.13770798697395378
Date
2020-03-13    67.102928
2020-03-16    58.470345
2020-03-17    61.041294
Name: AAPL, dtype: float64

Largest positive return:
Date: 2025-04-09 00:00:00
Return: 0.14261753799154478
Date
2025-04-08    171.513748
2025-04-09    197.804855
2025-04-10    189.419144
Name: AAPL, dtype: float64

============================================================
AMZN
============================================================

Largest negative return:
Date: 2022-04-29 00:00:00
Return: -0.15139791287665294
Date
2022-04-28    144.596497
2022-04-29    124.281502
2022-05-02    124.500000
Name: AMZN, dtype: float64

Largest positive return:
Date: 2022-02-04 00:00:00
Return: 0.1269489157684572
Date
2022-02-03    138.845505
2022-02-04    157.639496
2022-02-07    157.935501
Name: AMZN, dtype: float64

============================================================
GOOGL
============================================================

Largest negative return:
Date: 2020-03-16 00:00:00
Return: -0.12368444620079036
Date
2020-03-13    60.179867
2020-03-16    53.178459
2020-03-17    55.411648
Name: GOOGL, dtype: float64

Largest positive return:
Date: 2024-04-26 00:00:00
Return: 0.09734784661585123
Date
2024-04-25    154.628860
2024-04-26    170.438690
2024-04-29    164.689636
Name: GOOGL, dtype: float64

============================================================
JPM
============================================================

Largest negative return:
Date: 2020-03-16 00:00:00
Return: -0.16210602132052818
Date
2020-03-13    87.387894
2020-03-16    74.310387
2020-03-17    78.851761
Name: JPM, dtype: float64

Largest positive return:
Date: 2020-03-13 00:00:00
Return: 0.16562050213930363
Date
2020-03-12    74.049683
2020-03-13    87.387894
2020-03-16    74.310387
Name: JPM, dtype: float64

============================================================
META
============================================================

Largest negative return:
Date: 2022-02-03 00:00:00
Return: -0.3063907771860671
Date
2022-02-02    320.188324
2022-02-03    235.690277
2022-02-04    235.026093
Name: META, dtype: float64

Largest positive return:
Date: 2023-02-02 00:00:00
Return: 0.2093074973374677
Date
2023-02-01    151.787064
2023-02-02    187.126740
2023-02-03    184.906219
Name: META, dtype: float64

============================================================
MSFT
============================================================

Largest negative return:
Date: 2020-03-16 00:00:00
Return: -0.1594533976541503
Date
2020-03-13    150.547592
2020-03-16    128.358337
2020-03-17    138.926895
Name: MSFT, dtype: float64

Largest positive return:
Date: 2020-03-13 00:00:00
Return: 0.13292913288389402
Date
2020-03-12    131.808502
2020-03-13    150.547592
2020-03-16    128.358337
Name: MSFT, dtype: float64

============================================================
NVDA
============================================================

Largest negative return:
Date: 2020-03-16 00:00:00
Return: -0.2039794536220682
Date
2020-03-13    5.990503
2020-03-16    4.885130
2020-03-17    5.404238
Name: NVDA, dtype: float64

Largest positive return:
Date: 2023-05-25 00:00:00
Return: 0.2180878224043684
Date
2023-05-24    30.475473
2023-05-25    37.902233
2023-05-26    38.866261
Name: NVDA, dtype: float64

============================================================
TSLA
============================================================

Largest negative return:
Date: 2020-09-08 00:00:00
Return: -0.23651789445767657
Date
2020-09-04    139.440002
2020-09-08    110.070000
2020-09-09    122.093330
Name: TSLA, dtype: float64

Largest positive return:
Date: 2025-04-09 00:00:00
Return: 0.20449058000160142
Date
2025-04-08    221.860001
2025-04-09    272.200012
2025-04-10    252.399994
Name: TSLA, dtype: float64

============================================================
UNH
============================================================

Largest negative return:
Date: 2025-04-17 00:00:00
Return: -0.2533407580777855
Date
2025-04-16    565.763977
2025-04-17    439.147888
2025-04-21    411.316132
Name: UNH, dtype: float64

Largest positive return:
Date: 2020-03-24 00:00:00
Return: 0.12043667593726165
Date
2020-03-23    175.098022
2020-03-24    197.508698
2020-03-25    210.708939
Name: UNH, dtype: float64

============================================================
XOM
============================================================

Largest negative return:
Date: 2020-03-09 00:00:00
Return: -0.13039070476081002
Date
2020-03-06    36.125446
2020-03-09    31.709198
2020-03-10    32.883327
Name: XOM, dtype: float64

Largest positive return:
Date: 2020-03-24 00:00:00
Return: 0.11944189312129459
Date
2020-03-23    23.823561
2020-03-24    26.846003
2020-03-25    28.247396
Name: XOM, dtype: float64

Extreme Return Validation: Extreme daily log returns were identified and their corresponding adjusted prices and surrounding observations were examined. The extreme movements were consistent with genuine market or company-specific events, and no clear data-entry or extraction errors were detected. Therefore, no winsorization was applied, preserving genuine tail-risk information for subsequent risk modelling.

In [ ]:
# Align portfolio weights with return columns
aligned_weights = weights.reindex(clean_returns.columns)

print("=== ALIGNED PORTFOLIO WEIGHTS ===")
print(aligned_weights)

print("\nTotal weight:", aligned_weights.sum())

print("\nAny missing weights:",
      aligned_weights.isna().any())

=== ALIGNED PORTFOLIO WEIGHTS ===
Ticker
AAPL     0.1
AMZN     0.1
GOOGL    0.1
JPM      0.1
META     0.1
MSFT     0.1
NVDA     0.1
TSLA     0.1
UNH      0.1
XOM      0.1
Name: Weight, dtype: float64

Total weight: 1.0

Any missing weights: False

In [ ]:
# Calculate weighted daily portfolio log returns
portfolio_returns = clean_returns.mul(
    aligned_weights,
    axis=1
).sum(axis=1)

portfolio_returns.name = "Portfolio_Return"

print("Portfolio observations:", len(portfolio_returns))
print("\nFirst 10 portfolio returns:")
print(portfolio_returns.head(10))

print("\nMissing values:", portfolio_returns.isna().sum())

print("\nPortfolio return statistics:")
print(portfolio_returns.describe())

Portfolio observations: 1647

First 10 portfolio returns:
Date
2020-01-03   -0.006352
2020-01-06    0.010729
2020-01-07    0.000712
2020-01-08    0.010445
2020-01-09    0.005718
2020-01-10   -0.002367
2020-01-13    0.017252
2020-01-14   -0.003475
2020-01-15   -0.001877
2020-01-16    0.006784
Name: Portfolio_Return, dtype: float64

Missing values: 0

Portfolio return statistics:
count    1647.000000
mean        0.000883
std         0.016575
min        -0.149116
25%        -0.006341
50%         0.001812
75%         0.009351
max         0.112955
Name: Portfolio_Return, dtype: float64

In [ ]:
# Calculate 20-day rolling portfolio volatility
rolling_volatility = portfolio_returns.rolling(
    window=20
).std()

rolling_volatility.name = "Rolling_Volatility_20D"

print("Total observations:", len(rolling_volatility))
print("Missing observations:", rolling_volatility.isna().sum())

print("\nFirst 25 observations:")
print(rolling_volatility.head(25))

print("\nRolling volatility statistics:")
print(rolling_volatility.describe())

Total observations: 1647
Missing observations: 19

First 25 observations:
Date
2020-01-03         NaN
2020-01-06         NaN
2020-01-07         NaN
2020-01-08         NaN
2020-01-09         NaN
2020-01-10         NaN
2020-01-13         NaN
2020-01-14         NaN
2020-01-15         NaN
2020-01-16         NaN
2020-01-17         NaN
2020-01-21         NaN
2020-01-22         NaN
2020-01-23         NaN
2020-01-24         NaN
2020-01-27         NaN
2020-01-28         NaN
2020-01-29         NaN
2020-01-30         NaN
2020-01-31    0.010064
2020-02-03    0.011197
2020-02-04    0.012340
2020-02-05    0.012506
2020-02-06    0.012429
2020-02-07    0.012476
Name: Rolling_Volatility_20D, dtype: float64

Rolling volatility statistics:
count    1628.000000
mean        0.014538
std         0.008192
min         0.005568
25%         0.009697
50%         0.012309
75%         0.017669
max         0.066264
Name: Rolling_Volatility_20D, dtype: float64

In [ ]:
rolling_volatility_annual = rolling_volatility * np.sqrt(252)

rolling_volatility_annual.name = "Rolling_Volatility_20D_Annualized"

print(rolling_volatility_annual.describe())

count    1628.000000
mean        0.230788
std         0.130048
min         0.088387
25%         0.153932
50%         0.195401
75%         0.280488
max         1.051910
Name: Rolling_Volatility_20D_Annualized, dtype: float64

In [ ]:
# Save Phase 2 outputs

clean_prices.to_csv("Clean_Price_Matrix.csv")
clean_returns.to_csv("Clean_Return_Matrix.csv")

portfolio_returns.to_frame().to_csv(
    "Portfolio_Returns.csv"
)

rolling_volatility.to_frame().to_csv(
    "Rolling_Volatility_20D.csv"
)

rolling_volatility_annual.to_frame().to_csv(
    "Rolling_Volatility_20D_Annualized.csv"
)

print("Phase 2 files saved successfully.")

Phase 2 files saved successfully.

In [ ]:
print("=== PHASE 2 FINAL VALIDATION ===")

print("Clean prices:", clean_prices.shape)
print("Clean returns:", clean_returns.shape)
print("Portfolio returns:", portfolio_returns.shape)
print("Rolling volatility:", rolling_volatility.shape)

print("\nClean price missing values:",
      clean_prices.isna().sum().sum())

print("Clean return missing values:",
      clean_returns.isna().sum().sum())

print("Portfolio return missing values:",
      portfolio_returns.isna().sum())

print("Rolling volatility valid observations:",
      rolling_volatility.count())

print("Weights total:", aligned_weights.sum())

print("Dates aligned:",
      clean_prices.index.equals(clean_market.index))

=== PHASE 2 FINAL VALIDATION ===
Clean prices: (1648, 10)
Clean returns: (1647, 10)
Portfolio returns: (1647,)
Rolling volatility: (1647,)

Clean price missing values: 0
Clean return missing values: 0
Portfolio return missing values: 0
Rolling volatility valid observations: 1628
Weights total: 1.0
Dates aligned: True